// <auto-generated />
using CommerceTesteProj.Infrastructure.DataAcess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CommerceTesteProj.Presentation.Migrations
{
    [DbContext(typeof(ProdutoContext))]
    partial class ProdutoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("CommerceTesteProj.Domain.Models.Produto", b =>
                {
                    b.Property<int>("produto_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("nome")
                        .HasColumnType("TEXT");

                    b.Property<double>("qtde_estoque")
                        .HasColumnType("REAL");

                    b.Property<double>("valor_unitario")
                        .HasColumnType("REAL");

                    b.HasKey("produto_id");

                    b.ToTable("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
